name: Justin Garrison
markdown: redcarpet
pygments: true
baseurl:
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: /blog/page/:num
description: Blog by Justin Garrison
url: http://www.justingarrison.com
